# Stage 1: Build Environment
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package.json .
COPY package-lock.json .

# Install packages
RUN npm install

# Copy application source code
COPY . .

# Expose port 3000 where the React dev server runs
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]